// ─────────────────────────────────────────────────────────────────────────────
// exercises.js
// База упражнений. Чтобы добавить упражнение — просто добавь объект в массив.
//
// Поля:
//   id          — уникальный строковый идентификатор
//   name        — название на русском
//   type        — "kettlebell" | "bodyweight" | "mobility" | "stretching"
//   muscles     — массив групп мышц (для антиповтора смежных упражнений)
//   duration_sec — сколько секунд длится упражнение (для таймера)
//   rest_sec    — отдых после упражнения (0 для мобильности/растяжки)
//   intensity   — "high" | "medium" | "low"
//   weight_kg   — вес гири (null если без инвентаря)
//   sets_reps   — строка для отображения ("3×15", "60 сек каждая сторона" и т.д.)
//   notes       — подсказка по технике
// ─────────────────────────────────────────────────────────────────────────────

export const ALL_EXERCISES = [

    // ── ГИРЯ — СИЛА / КАРДИО ─────────────────────────────────────────────────
    {
      id: "kb_swing_two",
      name: "Махи гирей двумя руками",
      type: "kettlebell",
      muscles: ["glutes", "hamstrings", "lower_back", "core"],
      duration_sec: 40, rest_sec: 20, intensity: "high",
      weight_kg: 16, sets_reps: "3×15",
      notes: "Взрывной толчок бёдрами, не приседание",
    },
    {
      id: "kb_swing_one",
      name: "Махи гирей одной рукой",
      type: "kettlebell",
      muscles: ["glutes", "hamstrings", "core", "shoulders"],
      duration_sec: 40, rest_sec: 20, intensity: "high",
      weight_kg: 16, sets_reps: "3×10 каждая рука",
      notes: "Смена рук в верхней точке или после подхода",
    },
    {
      id: "kb_clean",
      name: "Подъём гири на грудь (Clean)",
      type: "kettlebell",
      muscles: ["glutes", "hamstrings", "traps", "forearms"],
      duration_sec: 45, rest_sec: 25, intensity: "medium",
      weight_kg: 16, sets_reps: "3×8 каждая рука",
      notes: "Гиря должна мягко ложиться на предплечье, не бить",
    },
    {
      id: "kb_press",
      name: "Жим гири стоя",
      type: "kettlebell",
      muscles: ["shoulders", "triceps", "core"],
      duration_sec: 40, rest_sec: 25, intensity: "medium",
      weight_kg: 16, sets_reps: "3×8 каждая рука",
      notes: "Напрячь кор и ягодицы, не прогибать поясницу",
    },
    {
      id: "kb_goblet_squat",
      name: "Приседание с гирей (Goblet)",
      type: "kettlebell",
      muscles: ["quads", "glutes", "core", "upper_back"],
      duration_sec: 40, rest_sec: 20, intensity: "medium",
      weight_kg: 16, sets_reps: "3×12",
      notes: "Колени разводить наружу, спина прямая",
    },
    {
      id: "kb_rdl",
      name: "Румынская тяга с гирей",
      type: "kettlebell",
      muscles: ["hamstrings", "glutes", "lower_back"],
      duration_sec: 40, rest_sec: 25, intensity: "medium",
      weight_kg: 16, sets_reps: "3×10",
      notes: "Мягкий сгиб колен, тянуть бёдрами назад",
    },
    {
      id: "kb_snatch",
      name: "Рывок гири",
      type: "kettlebell",
      muscles: ["glutes", "hamstrings", "shoulders", "core", "forearms"],
      duration_sec: 45, rest_sec: 30, intensity: "high",
      weight_kg: 16, sets_reps: "3×8 каждая рука",
      notes: "Требует техники — гиря не должна бить запястье",
    },
    {
      id: "kb_row",
      name: "Тяга гири в наклоне",
      type: "kettlebell",
      muscles: ["lats", "upper_back", "biceps", "core"],
      duration_sec: 40, rest_sec: 20, intensity: "medium",
      weight_kg: 16, sets_reps: "3×10 каждая рука",
      notes: "Локоть тянуть вдоль тела, не разводить в сторону",
    },
    {
      id: "kb_deadlift",
      name: "Становая тяга с гирей",
      type: "kettlebell",
      muscles: ["glutes", "hamstrings", "lower_back", "traps"],
      duration_sec: 40, rest_sec: 25, intensity: "medium",
      weight_kg: 16, sets_reps: "3×10",
      notes: "Гиря между стоп, спина нейтральна",
    },
    {
      id: "kb_farmers_carry",
      name: "Прогулка фермера",
      type: "kettlebell",
      muscles: ["forearms", "traps", "core", "glutes"],
      duration_sec: 40, rest_sec: 20, intensity: "medium",
      weight_kg: 16, sets_reps: "3×40 сек",
      notes: "Плечи назад, шаг уверенный",
    },
    {
      id: "kb_lunge",
      name: "Выпады с гирей",
      type: "kettlebell",
      muscles: ["quads", "glutes", "hamstrings", "core"],
      duration_sec: 45, rest_sec: 20, intensity: "medium",
      weight_kg: 16, sets_reps: "3×8 каждая нога",
      notes: "Гиря у груди, колено не выходит за носок",
    },
    {
      id: "kb_windmill",
      name: "Мельница с гирей",
      type: "kettlebell",
      muscles: ["core", "obliques", "shoulders", "hamstrings"],
      duration_sec: 45, rest_sec: 25, intensity: "medium",
      weight_kg: 16, sets_reps: "3×6 каждая сторона",
      notes: "Взгляд на гирю, движение медленное и контролируемое",
    },
    {
      id: "kb_halo",
      name: "Гало с гирей",
      type: "kettlebell",
      muscles: ["shoulders", "upper_back", "core"],
      duration_sec: 30, rest_sec: 15, intensity: "low",
      weight_kg: 16, sets_reps: "3×8 в каждую сторону",
      notes: "Круговое движение вокруг головы, держать гирю за рога",
    },
  
    // ── РАБОТА С ВЕСОМ ТЕЛА ───────────────────────────────────────────────────
    {
      id: "pushup",
      name: "Отжимания",
      type: "bodyweight",
      muscles: ["chest", "triceps", "shoulders", "core"],
      duration_sec: 40, rest_sec: 20, intensity: "medium",
      weight_kg: null, sets_reps: "3×12–15",
      notes: "Тело прямое как доска, локти 45° от тела",
    },
    {
      id: "pushup_wide",
      name: "Широкие отжимания",
      type: "bodyweight",
      muscles: ["chest", "shoulders", "triceps"],
      duration_sec: 40, rest_sec: 20, intensity: "medium",
      weight_kg: null, sets_reps: "3×12",
      notes: "Акцент на грудь",
    },
    {
      id: "plank",
      name: "Планка",
      type: "bodyweight",
      muscles: ["core", "shoulders", "glutes"],
      duration_sec: 30, rest_sec: 15, intensity: "low",
      weight_kg: null, sets_reps: "3×30–45 сек",
      notes: "Не поднимать таз, дышать ровно",
    },
    {
      id: "side_plank",
      name: "Боковая планка",
      type: "bodyweight",
      muscles: ["obliques", "core", "glutes"],
      duration_sec: 30, rest_sec: 15, intensity: "low",
      weight_kg: null, sets_reps: "2×30 сек каждая сторона",
      notes: "Таз не провисает",
    },
    {
      id: "hollow_body",
      name: "Hollow Body Hold",
      type: "bodyweight",
      muscles: ["core", "hip_flexors"],
      duration_sec: 30, rest_sec: 15, intensity: "medium",
      weight_kg: null, sets_reps: "3×20–30 сек",
      notes: "Поясница прижата к полу, ноги и руки вытянуты",
    },
    {
      id: "glute_bridge",
      name: "Ягодичный мостик",
      type: "bodyweight",
      muscles: ["glutes", "hamstrings", "core"],
      duration_sec: 35, rest_sec: 15, intensity: "low",
      weight_kg: null, sets_reps: "3×15",
      notes: "Сжимать ягодицы в верхней точке",
    },
    {
      id: "mountain_climber",
      name: "Скалолаз",
      type: "bodyweight",
      muscles: ["core", "shoulders", "hip_flexors"],
      duration_sec: 40, rest_sec: 20, intensity: "high",
      weight_kg: null, sets_reps: "3×30 сек",
      notes: "Бёдра не поднимать, темп высокий",
    },
    {
      id: "bear_crawl",
      name: "Медвежья походка",
      type: "bodyweight",
      muscles: ["core", "shoulders", "quads", "hip_flexors"],
      duration_sec: 40, rest_sec: 20, intensity: "medium",
      weight_kg: null, sets_reps: "3×10м вперёд-назад",
      notes: "Колени 2–3 см от пола, спина горизонтально",
    },
    {
      id: "burpee",
      name: "Бёрпи",
      type: "bodyweight",
      muscles: ["full_body"],
      duration_sec: 40, rest_sec: 30, intensity: "high",
      weight_kg: null, sets_reps: "3×8–10",
      notes: "Контролировать приземление, не горбиться",
    },
  
    // ── МОБИЛЬНОСТЬ СУСТАВОВ ──────────────────────────────────────────────────
    {
      id: "mob_thoracic_rotation",
      name: "Ротация грудного отдела",
      type: "mobility",
      muscles: ["upper_back", "obliques"],
      duration_sec: 60, rest_sec: 0, intensity: "low",
      weight_kg: null, sets_reps: "10 в каждую сторону",
      notes: "Лёжа на боку, колени 90°, верхняя рука тянется назад",
    },
    {
      id: "mob_hip_circle",
      name: "Круговые движения тазом",
      type: "mobility",
      muscles: ["hip_flexors", "glutes", "lower_back"],
      duration_sec: 45, rest_sec: 0, intensity: "low",
      weight_kg: null, sets_reps: "10 в каждую сторону",
      notes: "Стоя, руки на поясе, большой круг",
    },
    {
      id: "mob_ankle_circle",
      name: "Вращение голеностопа",
      type: "mobility",
      muscles: ["ankles"],
      duration_sec: 30, rest_sec: 0, intensity: "low",
      weight_kg: null, sets_reps: "10 в каждую сторону на каждую ногу",
      notes: "Сидя или стоя на одной ноге",
    },
    {
      id: "mob_shoulder_circle",
      name: "Вращение плечами",
      type: "mobility",
      muscles: ["shoulders", "upper_back"],
      duration_sec: 30, rest_sec: 0, intensity: "low",
      weight_kg: null, sets_reps: "10 вперёд + 10 назад",
      notes: "Медленно, с полной амплитудой",
    },
    {
      id: "mob_90_90",
      name: "90/90 — переключение",
      type: "mobility",
      muscles: ["hip_flexors", "glutes", "hip_external_rotators"],
      duration_sec: 60, rest_sec: 0, intensity: "low",
      weight_kg: null, sets_reps: "5–8 переключений в каждую сторону",
      notes: "Сидя на полу, оба колена 90°, переваливаться из стороны в сторону",
    },
    {
      id: "mob_world_greatest",
      name: "Лучшее упражнение в мире",
      type: "mobility",
      muscles: ["hip_flexors", "thoracic_spine", "hamstrings", "glutes"],
      duration_sec: 60, rest_sec: 0, intensity: "low",
      weight_kg: null, sets_reps: "5 повторений каждая сторона",
      notes: "Выпад + рука к потолку + разворот корпуса",
    },
    {
      id: "mob_cat_cow",
      name: "Кошка-корова",
      type: "mobility",
      muscles: ["spine", "core", "lower_back"],
      duration_sec: 45, rest_sec: 0, intensity: "low",
      weight_kg: null, sets_reps: "10 циклов",
      notes: "На четвереньках, дышать в ритм движения",
    },
    {
      id: "mob_deep_squat_hold",
      name: "Глубокий присед — удержание",
      type: "mobility",
      muscles: ["ankles", "hip_flexors", "lower_back", "glutes"],
      duration_sec: 60, rest_sec: 0, intensity: "low",
      weight_kg: null, sets_reps: "2×30–60 сек",
      notes: "Можно держаться за дверной косяк для баланса",
    },
    {
      id: "mob_inchworm",
      name: "Инчворм",
      type: "mobility",
      muscles: ["hamstrings", "shoulders", "core", "spine"],
      duration_sec: 45, rest_sec: 0, intensity: "low",
      weight_kg: null, sets_reps: "6–8 повторений",
      notes: "Из стойки — руки на пол — переход в планку — обратно",
    },
  
    // ── РАСТЯЖКА (статика — всегда в конце) ──────────────────────────────────
    {
      id: "str_hip_flexor",
      name: "Растяжка сгибателей бедра",
      type: "stretching",
      muscles: ["hip_flexors", "quads"],
      duration_sec: 60, rest_sec: 0, intensity: "low",
      weight_kg: null, sets_reps: "60 сек каждая сторона",
      notes: "Низкий выпад, таз вперёд, не прогибать поясницу",
    },
    {
      id: "str_hamstring",
      name: "Растяжка задней поверхности бедра",
      type: "stretching",
      muscles: ["hamstrings"],
      duration_sec: 60, rest_sec: 0, intensity: "low",
      weight_kg: null, sets_reps: "60 сек каждая нога",
      notes: "Лёжа на спине, нога вертикально, тянуть к себе",
    },
    {
      id: "str_pigeon",
      name: "Поза голубя",
      type: "stretching",
      muscles: ["glutes", "hip_external_rotators", "hip_flexors"],
      duration_sec: 90, rest_sec: 0, intensity: "low",
      weight_kg: null, sets_reps: "90 сек каждая сторона",
      notes: "Не заваливаться на одну сторону, сидеть ровно",
    },
    {
      id: "str_thoracic_open",
      name: "Раскрытие грудного отдела",
      type: "stretching",
      muscles: ["upper_back", "chest", "shoulders"],
      duration_sec: 60, rest_sec: 0, intensity: "low",
      weight_kg: null, sets_reps: "60 сек",
      notes: "Лёжа на ролике или скрученном полотенце под лопатками",
    },
    {
      id: "str_lat",
      name: "Растяжка широчайшей",
      type: "stretching",
      muscles: ["lats", "upper_back"],
      duration_sec: 45, rest_sec: 0, intensity: "low",
      weight_kg: null, sets_reps: "45 сек каждая сторона",
      notes: "Стоя у стены или стола, рука вверх, боковой наклон",
    },
    {
      id: "str_seated_twist",
      name: "Скручивание сидя",
      type: "stretching",
      muscles: ["spine", "obliques", "glutes"],
      duration_sec: 60, rest_sec: 0, intensity: "low",
      weight_kg: null, sets_reps: "60 сек каждая сторона",
      notes: "Сидя на полу, нога через колено, скручиваться от пупка",
    },
    {
      id: "str_child_pose",
      name: "Поза ребёнка",
      type: "stretching",
      muscles: ["lower_back", "lats", "glutes", "spine"],
      duration_sec: 60, rest_sec: 0, intensity: "low",
      weight_kg: null, sets_reps: "60 сек",
      notes: "Руки вперёд, лоб на полу, дышать в спину",
    },
  ];
  
  // Метаданные для UI
  export const TYPE_LABELS = {
    kettlebell: "Гиря",
    bodyweight: "Тело",
    mobility: "Мобильность",
    stretching: "Растяжка",
  };
  
  export const TYPE_COLORS = {
    kettlebell: "#e85d26",
    bodyweight: "#2563eb",
    mobility: "#16a34a",
    stretching: "#7c3aed",
  };
  
  export const INTENSITY_LABEL = {
    high: "Высокая",
    medium: "Средняя",
    low: "Низкая",
  };